project:
  type: website
  output-dir: docs

website:
  title: "Bobby Oliver Porfolio"
  
  navbar:
    right:
        - href: about.qmd
        - icon: github
          href: https://github.com/

format:
  html:
    
    theme: 
     light: spacelab
     dark: darkly
    css: styles.css
    toc: true

editor: visual


